<?php

namespace AppBundle\Repository;

/**
 * RideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RideRepository extends \Doctrine\ORM\EntityRepository
{
}
