<?php

/*
 * This file is part of the Symfony package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * RideRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RideRepository extends \Doctrine\ORM\EntityRepository
{
    public function getManyprotected(User $user)
    {
        return $this->createQueryBuilder('r')
            ->select('r')
            ->where('r.protectedUser = :id')
            ->setParameter('id', $user->getId())
            ->getQuery()
            ->getResult();
    }
}
