# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.normalizer.user:
        class: AppBundle\Serializer\Normalizer\UserNormalizer
        tags:
            - { name: serializer.normalizer }

    app.user_manager:
          class: AppBundle\Manager\UserManager
          arguments:
            - "@=service('doctrine').getManager()"

    app.avatar_manager:
        class: AppBundle\Manager\AvatarUserResolver
        arguments:
            - "@=service('doctrine').getManager()"

    app.birthday_manager:
        class: AppBundle\Manager\BirthdayUserResolver
        arguments:
            - "@=service('doctrine').getManager()"

    app.profil_manager:
        class: AppBundle\Manager\ProfileUserResolver
        arguments:
            - "@=service('doctrine').getManager()"

    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.form.profile:
        class: AppBundle\Form\UserProfileType
        tags:
            - { name: form.type, alias: app_user_profile }

    app.subscriber.check_user_pin:
        class: AppBundle\EventListener\RequestListener
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - "@router"
            - "@security.authorization_checker"
            - "@security.token_storage"

    app.twig.avatar_extension:
        class: AppBundle\Twig\AvatarExtension
        tags:
        - { name: twig.extension }
        arguments:
            - "@app.avatar_manager"

    app.twig.birthday_extension:
        class: AppBundle\Twig\BirthdayExtension
        tags:
        - { name: twig.extension }
        arguments:
            - "@app.birthday_manager"

    app.twig.profil_extension:
        class: AppBundle\Twig\ProfilExtension
        tags:
        - { name: twig.extension }
        arguments:
            - "@app.profil_manager"

