# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.normalizer.user:
        class: AppBundle\Serializer\Normalizer\UserNormalizer
        tags:
            - { name: serializer.normalizer }

    app.user_manager:
          class: AppBundle\Manager\UserManager
          arguments:
            - "@=service('doctrine').getManager()"

    app.avatar_manager:
        class: AppBundle\Manager\AvatarUserResolver
        arguments:
            - "@=service('doctrine').getManager()"

    app.birthday_manager:
        class: AppBundle\Manager\BirthdayUserResolver
        arguments:
            - "@=service('doctrine').getManager()"

    app.profil_manager:
        class: AppBundle\Manager\ProfileUserResolver
        arguments:
            - "@=service('doctrine').getManager()"

    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.form.profile:
        class: AppBundle\Form\UserEditProfileType
        tags:
            - { name: form.type, alias: app_user_profile }

    app.subscriber.check_user_pin:
        class: AppBundle\EventListener\RequestListener
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - "@router"
            - "@security.authorization_checker"
            - "@security.token_storage"

    app.twig.avatar_extension:
        class: AppBundle\Twig\AvatarExtension
        tags:
        - { name: twig.extension }
        arguments:
            - "@app.avatar_manager"

    app.twig.birthday_extension:
        class: AppBundle\Twig\BirthdayExtension
        tags:
        - { name: twig.extension }
        arguments:
            - "@app.birthday_manager"

    app.twig.profil_extension:
        class: AppBundle\Twig\ProfilExtension
        tags:
        - { name: twig.extension }
        arguments:
            - "@app.profil_manager"

    hwi_oauth.user.provider.entity:
            class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider

    app.fos_user.oauth_provider:
            class: AppBundle\Security\Core\User\MyFOSUBUserProvider
            arguments: ["@fos_user.user_manager",{facebook: facebookId},"@app.facebook_friends_service"]

    my.oauth_aware.user_provider.service:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\FOSUBUserProvider
        arguments:
            - '@fos_user.user_manager'
            - ['pass properties as array']

    app.facebook_friends_service:
        class: AppBundle\Service\FacebookFriends
        arguments:
            - "@app.user_manager"

    admin.category:
            class: AppBundle\Admin\PictureAdmin
            arguments: [~, AppBundle\Entity\Picture, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Pictures , group : Picture}

    admin.user:
            class: AppBundle\Admin\UserAdmin
            arguments: [~, AppBundle\Entity\User, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: List User, group : User }

    app.picture_uploader:
          class: AppBundle\Service\PictureUploader
          arguments:
              - '%pictures_directory%'
              - "@=service('doctrine').getManager()"

    app.address_manager:
        class: AppBundle\Manager\AddressManager
        arguments:
            - "@=service('doctrine').getManager()"

