# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.subscriber.check_user_pin:
        class: AppBundle\EventListener\RequestListener
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - "@router"
            - "@security.authorization_checker"
            - "@security.token_storage"