# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.normalizer.user:
        class: AppBundle\Serializer\Normalizer\UserNormalizer
        tags:
            - { name: serializer.normalizer }

    app.user_manager:
          class: AppBundle\Manager\UserManager
          arguments:
            - "@=service('doctrine').getManager()"